---
- name: Configure Apache web server
  hosts: all
  become: yes
  tasks:
    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy custom index.html
      copy:
        src: /home/ansible/task4/index.html  # Source file path
        dest: /var/www/html/index.html       # Apache default docroot
        owner: root
        group: root
        mode: 0644
      notify: Restart Apache

    - name: Verify Apache serves the new page
      uri:
        url: "http://localhost"
        return_content: yes
      register: webpage
      failed_when: "'Welcome' not in webpage.content"  # Change to expected text

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted